# Generated by Django 5.0.1 on 2024-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_content',
            field=models.TextField(),
        ),
    ]
